### ISSUE TITLE
[error]	server:49 ParserIncomingMessage is not a constructor

### ISSUE THREAD

**Issue by AlexandreSousa** [localtunnel/server#83]
[error]	server:49 ParserIncomingMessage is not a constructor
TypeError: ParserIncomingMessage is not a constructor
    at HTTPParser.parserOnHeadersComplete (_http_common.js:81:21)
    at Socket.socketOnData (_http_client.js:444:20)
    at Socket.emit (events.js:127:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:598:20)

**Comment by notoriaga** [comment]
I'm getting the same thing. Did you figure out a way around it @AlexandreSousa?

**Comment by defunctzombie** [comment]
This is happening on newer versions of nodejs. Only the version specified in the Dockerfile is supported at any given time :)

**Comment by panlina** [comment]
Same here.
I dig into it and found the error happens here:
https://github.com/nodejs/node/blob/v8.12.0/lib/_http_common.js#L77
I'm referencing the source in v8.12.0 since it's the 1st release that introduces `ParserIncomingMessage`.
v8.11.4 uses `IncomingMessage` directly:
https://github.com/nodejs/node/blob/v8.11.4/lib/_http_common.js#L76
v9.0.0 does not have `ParserIncomingMessage` either:
https://github.com/nodejs/node/blob/v9.0.0/lib/_http_common.js#L78
v10.0.0 introduced `ParserIncomingMessage` again:
https://github.com/nodejs/node/blob/v10.0.0/lib/_http_common.js#L80
As I tested, this issue exists for v8.12.0, and does not exist for v8.11.4. So I believe the same applies to v9.0.0 and v10.0.0.
I've no idea why nodejs had these changes and why this issue is triggered on those versions.
This is making this project hard to work with because it depends on the node version in the environment, in a very inconsistent manner(works for v8.11.4, but not for v8.12.0, works again for v9.0.0, not again for v10.0.0). Does anyone has any clue how this issue happens?
